spring:
  application:
    name: crud-operations
  datasource:
    url : jdbc:postgresql://localhost:5432/demopost
    username : postgres
    password : admin
  jpa:
    hibernate:
      ddl-auto : update
    show-sql : true
#spring.jpa.properties.hibernate.generate_statistics=true
#logging.level.org.hibernate.stat=debug

